version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      runas: ec2-user