version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/concierge
permissions:
  - object: /home/ubuntu/concierge
    owner: ubuntu
    group: ubuntu
    mode: 744
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/run.sh
      runas: ubuntu